sample-code/examples/java/junit/pom.xml
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidContactsTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidWebViewTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/MobileFindJavaTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/SauceTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/SimpleTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/UICatalogTest.java

Updated appium java-client sauce_junit, JDK and iOS versions

Updated java sample code dependencies

---

sample-code/examples/dotnet/AppiumDotNetSample/AndroidComplexTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidConnectionTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidOrientationTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidSimpleTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidWebviewTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AppiumDotNetSample.csproj
sample-code/examples/dotnet/AppiumDotNetSample/IosActionsTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosComplexTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosLocalServerTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosOrientationTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosSimpleTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosWebviewTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/helpers/Caps.cs
sample-code/examples/dotnet/AppiumDotNetSample/packages.config

It was synchronized with the latest version (1.2.0.7) of the library for
C#.

.Net sample actualization.

---

.gitignore
sample-code/examples/python/README.md
sample-code/examples/python/android_gestures_sauce.py
sample-code/examples/python/android_sauce.py
sample-code/examples/python/ios_sauce.py
sample-code/examples/python/ios_sauce_webview.py

Use the new base class for Sauce Labs tests. Also add a test on Sauce that does complex gestures on Android.

Fix Sauce Labs test in Python

---

sample-code/examples/ruby/android_on_sauce.rb

there is a bug in pre 1.3.4 that cause this to fail, updating to 1.3.4

Update Appium version

---

sample-code/examples/python/ios_complex.py
sample-code/examples/python/ios_simple.py

** Only fixed the ones that does not work
- Change version to 8.3
- Fix according to changes in test application.
- Fix path for items

Fix tests for ios_simple , os_complex.

---

sample-code/examples/node/ios-yiewd.js

add missing period. fails without it.

fix ios-yiewd.js

---

sample-code/examples/java/junit/pom.xml
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidContactsTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidPageObjectTest_ByAllPossible.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidPageObjectTest_Chained.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidPageObjectTest_PageObjectLikeComplexElement.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidPageObjectTest_Simple.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidWebViewTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/MobileFindJavaTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/SafariTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/SauceTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/SimpleTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/UICatalogTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/iOSPageObjectTest.java

Java samles have been synchronized with java_client v3.0

Synchronization with java_client v3.0

---

sample-code/examples/ruby/simple_test.rb

Fixing Timing issue with alert box appearance

---

sample-code/examples/dotnet/AppiumDotNetSample/AndroidComplexTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidLocalServerTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidLocationTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidOrientationTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidSimpleTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidWebviewTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AppiumDotNetSample.csproj
sample-code/examples/dotnet/AppiumDotNetSample/IOSLocationTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosActionsTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosComplexTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosLocalServerTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosOrientationTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosSimpleTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosWebviewTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/helpers/Actions.cs
sample-code/examples/dotnet/AppiumDotNetSample/helpers/Env.cs
sample-code/examples/dotnet/AppiumDotNetSample/helpers/Filters.cs
sample-code/examples/dotnet/AppiumDotNetSample/helpers/LocalServer.cs
sample-code/examples/dotnet/AppiumDotNetSample/packages.config

The sample .NET project was updated to 1.3.0.1 version of
appium-net-driver

Update of the .NET  sample to the new version

---

sample-code/examples/php/SimpleTest.php

* locator strategy has changed
* dir name does not have an uppercase
* definitions of the capabilities changed

Make the SimpleTest works with appium 1.4.8 / iOS 8.4

---

sample-code/examples/dotnet/AppiumDotNetSample/AndroidGestureTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AppiumDotNetSample.csproj
sample-code/examples/dotnet/AppiumDotNetSample/IosGestureTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/AndroidNativeAppAttributesTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/AndroidTestThatChecksAttributeMix1.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/AndroidTestThatChecksAttributeMix2.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/AndroidTestThatChecksAttributeMix3SelendroidMode.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/AndroidWebViewTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/SeleniumAttributesCompatipilityTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/DesktopBrowserCompatibility/DesctopBrowserCompatibilityTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/IOS/IOSNativeAppAttributesTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/IOS/IOSTestThatChecksAttributeMix.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/README.md
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/TimeOutManagement/TimeOutManagementTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/AndroidPageObjectChecksAttributeMixOnNativeApp1.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/AndroidPageObjectChecksAttributeMixOnNativeApp2.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/AndroidPageObjectChecksAttributesForNativeAndroidApp.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/AndroidPageObjectChecksSelendroidModeOnNativeApp.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/AndroidPageObjectChecksSeleniumFindsByCompatibility.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/AndroidWebView.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/IOSPageObjectChecksAttributeMixOnNativeApp.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/IOSPageObjectChecksAttributesForNativeIOSApp.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/README.md
sample-code/examples/dotnet/AppiumDotNetSample/packages.config

Now it shows capabilities of the latest stable release.

.Net sample was updated to release 1.4.0.2

---

sample-code/examples/dotnet/AppiumDotNetSample/helpers/Apps.cs
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/SimpleTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/UICatalogTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/iOSPageObjectTest.java
sample-code/examples/node/helpers/apps.js
sample-code/examples/perl/ios_simple.pl
sample-code/examples/python/ios_complex.py
sample-code/examples/python/ios_simple.py
sample-code/examples/python/ios_webview.py

so these examples were looking for TestApp in the wrong directory

bugfix: "Release-" has  been changed to to "release-",

---

sample-code/examples/java/junit/pom.xml
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidPageObjectTest_ByAllPossible.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidPageObjectTest_Chained.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidPageObjectTest_PageObjectLikeComplexElement.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidPageObjectTest_TimeOutManagement.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/driver_service/DriverServiceSample.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/driver_service/custom_node_path.properties
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/iOSPageObjectTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object/PageObjectWithCustomizedTimeOuts.java

- Now feateres of 3.1.0 are demonstrated
- The demonstration of features of 3.2.0 was added

Update java sample

---

sample-code/examples/dotnet/AppiumDotNetSample/AndroidComplexTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidConnectionTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidGestureTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidLocalServerTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidOrientationTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidSimpleTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AndroidWebviewTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/AppiumDotNetSample.csproj
sample-code/examples/dotnet/AppiumDotNetSample/IosActionsTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosComplexTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosGestureTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosLocalServerTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosOrientationTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosSimpleTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/IosWebviewTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/AndroidNativeAppAttributesTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/AndroidTestThatChecksAttributeMix1.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/AndroidTestThatChecksAttributeMix2.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/AndroidTestThatChecksAttributeMix3SelendroidMode.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/AndroidWebViewTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/Android/SeleniumAttributesCompatipilityTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/DesktopBrowserCompatibility/DesctopBrowserCompatibilityTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/IOS/IOSNativeAppAttributesTest.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjectTests/IOS/IOSTestThatChecksAttributeMix.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/AndroidPageObjectChecksSeleniumFindsByCompatibility.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/AndroidWebView.cs
sample-code/examples/dotnet/AppiumDotNetSample/PageObjects/IOSPageObjectChecksAttributesForNativeIOSApp.cs
sample-code/examples/dotnet/AppiumDotNetSample/packages.config

- Update to  Appium .Net client v1.4.1.1
- unused imports were removed

Update to  Appium .Net client v1.4.1.1

---

sample-code/examples/node/helpers/caps.js
sample-code/examples/node/ios-simple.js

update platform version example for Xcode 7.2.1
https://github.com/appium/sample-code/issues/55

Update simple node example for xcode 7.2.1

---

sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidDragAndDrop.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidSlideTest.java

added DragAndDropTest and SliderTest for Android

---

sample-code/examples/java/junit/pom.xml
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidPageObjectTest_Simple.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/SafariTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/SauceTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/SimpleTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/UICatalogTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/driver_service/DriverServiceSample.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/driver_service/custom_node_path.properties
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/iOSPageObjectTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object/ios/TestAppScreenSimple.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object/widgets/SelendroidOverrideWidgetTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object/widgets/combined/SelendroidCombinedWidgetTest.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object/widgets/selendroid/SelendroidWidgetTest.java

I have fixed some of the test cases under Jave repo.
Main Changes
1. updated latest Java Client version
2. Removed compilation errors
3. updated element identifiers
Please review changes and merge.
Thanks & Regards,
Vikram

First round of fixes for java related examples

---

sample-code/examples/C#/CalculatorTest/BasicScenarios.cs
sample-code/examples/C#/CalculatorTest/CalculatorTest.csproj
sample-code/examples/C#/CalculatorTest/CalculatorTest.sln
sample-code/examples/C#/CalculatorTest/Properties/AssemblyInfo.cs
sample-code/examples/C#/CalculatorTest/app.config
sample-code/examples/C#/CalculatorTest/packages.config
sample-code/examples/java/Windows/pom.xml
sample-code/examples/java/Windows/src/test/java/CalculatorTest.java
sample-code/examples/python/windows_calculatortest.py
sample-code/examples/ruby/windows_CalculatorTest.rb

Adding Samples to test Windows Desktop applications using Appium. Samples in the following languages:
-Python
-Ruby
-Java
-C#

Adding Windows samples to Appium sample code repo

---

sample-code/examples/RobotFramework/test_android_contact_resource.txt

Currently, the test is not woking in Mac, ID's that are being called in the file are not in the APP, so they produce an error in the test

Update test_android_contact_resource.txt file

---

sample-code/examples/node/android-webview.js
sample-code/examples/node/helpers/local-server.js
sample-code/examples/node/package.json

Removes from package.json script for non-existent test android-actions.js
Adds in package.json script for existing test android-local-server.js
Fixes asset reference for http download in android-local-server test
Fixes XPath selector error in android-webview test, bit test still fails overall

Fixes Node test issues

---

sample-code/examples/python/pytest/README.md
sample-code/examples/python/pytest/conftest.py
sample-code/examples/python/pytest/helpers.py
sample-code/examples/python/pytest/requirements.txt
sample-code/examples/python/pytest/test_android_contacts.py
sample-code/examples/python/pytest/test_android_simple_with_logs.py

Added Python pytest fixture examples from issue #110

#110 add python pytest fixture examples

---

sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/BaseCrossPlatformDriver.java
sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/GestureTest.java

* LongPressTest
* swipeTest
* DoubleTapTest

added gesture test
